Repository preludeorg/operator-support, pull requests merged in 2021-07, with the labels that each got.

#269 checking response codes when doing deploys from cloud plugin
  plugins/Cloud/Cloud.html
Labels: size/S

#268 re-enabling tools on cloud plugin
  plugins/Cloud/Cloud.html
Labels: size/M

#270 simple FTP translator
  translators/README.md
  translators/ftp/README.md
  translators/ftp/agent.py
  translators/ftp/server.py
Labels: size/L

#274 adding requirements files for translators
  translators/ftp/requirements.txt
  translators/grpc/requirements.txt
Labels: size/XS

#293 fixing broken change handler
  plugins/Navigator/Navigator.html
Labels: size/XS

#294 remove global usage in plugin
  plugins/AzureInitialAccess/AzureInitialAccess.html
Labels: size/M
