Repository preludeorg/operator-support, pull requests merged in 2021-06, with the labels that each got.

#211 fixing toolbox bugs
  plugins/Toolbox/Toolbox.html
Labels: size/S

#210 Adding configuration dock item; cleaning up deployment
  plugins/Cloud/Cloud.html
Labels: size/M

#213 Final tweaks to elastic provisioning to handle agents joining an exis…
  plugins/Cloud/Cloud.html
Labels: size/S

#215 Fix cloud element hiding/visibility
  plugins/Cloud/Cloud.html
Labels: size/XS

#216 Hook existing sidebar for elements
  plugins/Cloud/Cloud.html
Labels: size/L

#217 fixing cloud plugin loading
  plugins/Cloud/Cloud.html
Labels: size/S

#224 fixing cloud and azure plugins
  plugins/AzureInitialAccess/AzureInitialAccess.html
  plugins/Cloud/Cloud.html
Labels: size/XS

#229 Removing stale code throwing error
  plugins/AzureInitialAccess/AzureInitialAccess.html
Labels: size/XS

#231 fixing navigator 404
  plugins/Navigator/Navigator.html
Labels: size/XS

#233 Reload plugin sidebar elements on click
  plugins/Cloud/Cloud.html
Labels: size/L

#236 fixing cloud plugin sidebar and deployment button handlers
  plugins/Cloud/Cloud.html
Labels: size/L

#238 Update Toolbox.html
  plugins/Toolbox/Toolbox.html
Labels: size/S

#240 cleaning up Cloud plugin so that reload & overlays don't fire out of …
  plugins/Cloud/Cloud.html
Labels: size/L

#248 Fixed importing ART tests
  plugins/ART/ART.html
Labels: size/XS

#249 fixing bottom padding on imported TTP panels
  plugins/ART/ART.html
Labels: size/XS

#256 giving each command its own set of dependencies
  plugins/ART/ART.html
Labels: size/S
