Repository preludeorg/operator-support, pull requests merged in 2021-03, with the labels that each got.

#124 Single Toggle button for ThemeChange plugin
  plugins/themechange/ThemeChange.html
  plugins/themechange/config.yml
Labels: size/S

#125 Fixing Margins on Navigator Plugin
  plugins/navigator/Navigator.html
  plugins/navigator/config.yml
Labels: size/XS

#126 Add an availability notification to the tunnel
  plugins/cloud/Cloud.html
  plugins/cloud/config.yml
Labels: size/M

#127 adding redirector destruction back
  plugins/cloud/Cloud.html
  plugins/cloud/config.yml
Labels: size/M

#129 Adding patch to fix upgrade from old versions on windows to 0.9.17
  upgrade-patch-0.9.17.ps1
Labels: size/XS

#133 Provisioning splunk range through the cloud plugin
  plugins/cloud/Cloud.html
  plugins/cloud/config.yml
Labels: size/M

#137 Update Cloud.html
  plugins/cloud/Cloud.html
  plugins/cloud/config.yml
Labels: size/XS
