Repository preludeorg/operator-support, pull requests merged in 2021-04, with the labels that each got.

#145 checking agent license and showing note
  plugins/agentlibrary/AgentLibrary.html
  plugins/agentlibrary/config.yml
Labels: size/S

#141 Switchboard support
  plugins/cloud/Cloud.html
  plugins/cloud/config.yml
Labels: size/S

#152 adding themed backgrounds!
  plugins/themechange/ThemeChange.html
  plugins/themechange/config.yml
Labels: size/M

#154 Random background changer
  plugins/themechange/ThemeChange.html
  plugins/themechange/config.yml
Labels: size/S

#162 Adding adversary generation via Navigator layer
  plugins/navigator/Navigator.html
  plugins/navigator/config.yml
Labels: size/M

#168 tweaking a few parts of the nav plugin
  plugins/navigator/Navigator.html
Labels: size/S

#166 adding a plugin for importing atomic red team ttps
  plugins/art/ART.html
Labels: size/L

#169 art.fact regex replacement
  plugins/art/ART.html
Labels: size/XS

#171 adding new toolbox plugin for managing local repos
  plugins/art/ART.html
  plugins/art/config.yml
  plugins/toolbox/Toolbox.html
  plugins/toolbox/config.yml
Labels: size/L

#173 adding a starter kit to toolbox
  plugins/toolbox/Toolbox.html
Labels: size/M
