Repository preludeorg/operator-support, pull requests merged in 2021-05, with the labels that each got.

#174 navigator 4.3 update
  plugins/navigator/template.json
Labels: size/S

#175 squashing bug
  plugins/art/ART.html
Labels: size/XS

#182 Using API endpoints
  plugins/themechange/ThemeChange.html
  plugins/themechange/config.yml
Labels: size/S

#181 patching navigator to use new API endpoints
  plugins/navigator/Navigator.html
  plugins/navigator/config.yml
Labels: size/L

#180 adding tools as a param to range provisioning
  plugins/cloud/Cloud.html
Labels: size/XS

#184 asking GK for the range options
  plugins/cloud/Cloud.html
Labels: size/S

#185 Using API endpoints and resolving merge conflicts
  plugins/cloud/Cloud.html
  plugins/cloud/config.yml
Labels: size/XL

#190 Update AgentLibrary.html
  plugins/agentlibrary/AgentLibrary.html
  plugins/agentlibrary/config.yml
Labels: size/L

#191 killing the init block
  plugins/agentlibrary/AgentLibrary.html
Labels: size/XS

#192 removing config files from plugins
  plugins/agentlibrary/config.yml
  plugins/art/config.yml
  plugins/cloud/config.yml
  plugins/navigator/config.yml
  plugins/themechange/config.yml
  plugins/toolbox/config.yml
  upgrade-patch-0.9.17.ps1
Labels: size/S

#194 Using /internal/global/redirectors instead of /internal/config/redirectors
  plugins/cloud/Cloud.html
Labels: size/XS

#195 No more monkey
  plugins/art/ART.html
Labels: size/XS

#193 Using SETTINGS api
  plugins/toolbox/Toolbox.html
Labels: size/L

#196 removing div from toolbox
  plugins/toolbox/Toolbox.html
Labels: size/XS

#197 fixing plugins around api funcs
  plugins/art/ART.html
  plugins/navigator/Navigator.html
  plugins/themechange/ThemeChange.html
Labels: size/M

#198 Local source js
  plugins/toolbox/Toolbox.html
  plugins/toolbox/showdown.min.js
Labels: size/XS

#199 more patches
  plugins/cloud/Cloud.html
  plugins/toolbox/Toolbox.html
Labels: size/M

#200 Exposing Cloud Tools Toggles
  plugins/cloud/Cloud.html
Labels: size/M

#201 refactoring the cloud plugin to be more intutitive
  plugins/cloud/Cloud.html
Labels: size/L

#187 Adding an Azure initial access plugin to deploy agents on Azure Virtu…
  plugins/azureinitialaccess/AzureInitialAccess.html
Labels: size/XL

#202 Update Toolbox.html
  plugins/toolbox/Toolbox.html
Labels: size/L

#208 Making cloud call SIEM endpoint instead of discrete endpoints per SIEM
  plugins/Cloud/Cloud.html
Labels: size/M
